<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/>
    </parent>

    <groupId>com.ust.day4</groupId>
    <artifactId>day4-kafka-assignments</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>day4-kafka-assignments</name>

    <modules>
        <module>ecommerce/order-service</module>
        <module>ecommerce/notification-service</module>
        <module>ecommerce/inventory-service</module>
        <module>banking/transaction-service</module>
        <module>banking/fraud-service</module>
        <module>banking/alert-service</module>
        <module>movie/booking-service</module>
        <module>movie/payment-service</module>
        <module>movie/email-service</module>
    </modules>

    <properties>
        <java.version>17</java.version>
    </properties>
</project>
